
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests (Optional)
          command: npm test
      - run:
          name: Lint Code (Optional)
          command: npm run lint
      - run:
          name: Build Application
          command: npm run build
workflows:
  build_and_deploy:
    jobs:
      - build
