
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@7.1.0

jobs:
  build:
    executor: node/default
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run deploy

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

